/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesTopicRouteImport } from './routes/resources.$topic'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTopicRoute = ResourcesTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/tips': typeof TipsRoute
  '/resources/$topic': typeof ResourcesTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/tips': typeof TipsRoute
  '/resources/$topic': typeof ResourcesTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/tips': typeof TipsRoute
  '/resources/$topic': typeof ResourcesTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/legal'
    | '/onboarding'
    | '/profile'
    | '/resources'
    | '/tips'
    | '/resources/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/legal'
    | '/onboarding'
    | '/profile'
    | '/resources'
    | '/tips'
    | '/resources/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assistant'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/legal'
    | '/onboarding'
    | '/profile'
    | '/resources'
    | '/tips'
    | '/resources/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LegalRoute: typeof LegalRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  TipsRoute: typeof TipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$topic': {
      id: '/resources/$topic'
      path: '/$topic'
      fullPath: '/resources/$topic'
      preLoaderRoute: typeof ResourcesTopicRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesTopicRoute: typeof ResourcesTopicRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesTopicRoute: ResourcesTopicRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LegalRoute: LegalRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  TipsRoute: TipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
